name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: List directory contents before Nuclei run
      run: ls -la /home/runner/work/Volopay-Faster-Vite/Volopay-Faster-Vite/

    - name: Install Nuclei
      run: |
        mkdir -p /home/runner/work/Volopay-Faster-Vite/Volopay-Faster-Vite
        cd /home/runner/work/Volopay-Faster-Vite/Volopay-Faster-Vite
        wget https://github.com/projectdiscovery/nuclei/releases/download/v2.6.3/nuclei_2.6.3_linux_amd64.tar.gz
        tar -xzvf nuclei_2.6.3_linux_amd64.tar.gz
        sudo mv nuclei /usr/local/bin/
    # - name: Run Nuclei
    #   uses: projectdiscovery/nuclei-action@main

    - name: Create Nuclei config directory
      run: mkdir -p /home/runner/work/Volopay-Faster-Vite/Volopay-Faster-Vite

    - name: Create Nuclei config file
      run: echo "your nuclei config content" > /home/runner/work/Volopay-Faster-Vite/Volopay-Faster-Vite/config.yaml

    - name: List directory contents after creating config file
      run: ls -la /home/runner/work/Volopay-Faster-Vite/Volopay-Faster-Vite/

    - name: Run Nuclei with config
      run: nuclei -config /home/runner/work/Volopay-Faster-Vite/Volopay-Faster-Vite/config.yaml
